SFPracticeApp/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFPracticeApp/main/default/objects/Certification__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SFPracticeApp/main/default/objects/Certification__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resources__c</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

SFPracticeApp/main/default/objects/Certification__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/objects/Historical_Certification__c/Historical_Certification__c.object-meta.xml
<CustomObject>
    <label>Historical Certification</label>
    <nameField>
        <label>Historical Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historical Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFPracticeApp/main/default/objects/Historical_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <label>Certification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/objects/Historical_Certification__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resources__c</referenceTo>
    <relationshipLabel>Historical Certifications</relationshipLabel>
    <relationshipName>Historical_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

SFPracticeApp/main/default/objects/Historical_Certification__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/classes/BatchCopyToHistorical.cls
//this batch class has to run on after delete
public class BatchCopyToHistorical implements Database.Batchable<sObject> {
    //this map will carry the certs to act upon
    map<id,Certification__c> certM = new map<id,Certification__c>();
    //populate the certs to bulkify
    public BatchCopyToHistorical(map<id,Certification__c> certMapP){
        certM = certMapP;
}
    public database.QueryLocator start(Database.BatchableContext bc) {
        
        //create cert scope based on parameter cert set
        return database.getQueryLocator([SELECT City__c, Country__c, 
        Email__c, Id, Name, Name__c, Period__c, Resource__c, State_Province__c, Status__c, Type__c
        FROM Certification__c where id in :certM.keySet()]); 
    }

    public void execute(Database.BatchableContext bc, list<Certification__c> scope){
        //create a certhist to later DML insert
        list<Historical_Certification__c> histL = new list<Historical_Certification__c>();
        //fill up the histcert list
        for(Certification__c certF: scope){
            histl.add(new Historical_Certification__c(
                        City__c = certF.City__c,
                        Country__c = certF.Country__c,
                        Email__c = certF.Email__c,
                        Name = certF.Name,
                        Certification__c = certF.Name,
                        name__c = certF.name__c,
                        Period__c = certF.Period__c,
                        resource__c = certF.resource__c,
                        State_Province__c = certF.State_Province__c,
                        Status__c = certF.Status__c,
                        Type__c = certF.Type__c
            ));
        }
        //insert the list
        insert histL;
    }
    public void finish(Database.BatchableContext bc){
        //upon finish, run linking to resources on certs
        BatchLinkCertToRes myBatch = new BatchLinkCertToRes(certM);
        Database.executeBatch(myBatch);

    }
}