SFPracticeApp/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFPracticeApp/main/default/objects/Certification__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SFPracticeApp/main/default/objects/Certification__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resources__c</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

SFPracticeApp/main/default/objects/Certification__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/objects/Resources__c/Resources__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>EMP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFPracticeApp/main/default/objects/Resources__c/fields/Employee_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email_Id__c</fullName>
    <label>Employee Email Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/objects/Resources__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFPracticeApp/main/default/objects/Resources__c/fields/Webassessor_Email__c.field-meta.xml
<CustomField>
    <fullName>Webassessor_Email__c</fullName>
    <label>Webassessor Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFPracticeApp/main/default/classes/BatchLinkCertToRes.cls
//this class will link certs to resources
public class BatchLinkCertToRes implements Database.Batchable<sObject> {
    //create certification map to bulkify
    map<id,Certification__c> certM = new map<id,Certification__c>();
    //constructor to initialize map
    public BatchLinkCertToRes(map<id,Certification__c> certMapP){
        certM = certMapP;
}
    public Database.QueryLocator start(Database.BatchableContext bc) {
        //create scope based on bulkification map
        return database.getQueryLocator([SELECT City__c, Country__c, 
        Email__c, Id, Name, Name__c, Period__c, Resource__c, State_Province__c, Status__c, Type__c
        FROM Certification__c where id in :certM.keySet()]); 
    }

    public void execute(Database.BatchableContext bc, List<Certification__c> scope){
    	//get a full list of resources
        List<Resources__c> resL = [select id, webassessor_email__c, employee_email_id__c from resources__c];
       

        //create a string string map
        Map<string, string> resM = new Map<string, string>();

        //loop through all resources to build a map with their email as key and id as getter
        for(Resources__c resF:resL){
            resM.put(resF.Webassessor_Email__c , resF.Id);
        }

        //loop through certs and assign back
        for(Certification__c certF:scope){
            certf.Resource__c = resM.get(certF.Email__c);
        }
        //DML
        update scope;
    }

    public void finish(Database.BatchableContext bc){
        //upon finish, count the certs on the res
        BatchCountCertsOnRes myBatch = new BatchCountCertsOnRes(certM);
        database.executeBatch(myBatch);

    }
}